### ISSUE TITLE
Error: Got RST: CANCEL

### ISSUE THREAD

**Issue by ronkorving** [indutny/spdy-transport#19]
Hi,

I was connected with Chrome and don't remember doing anything funky, but all of the sudden I noticed the following printed in my Node terminal:

```
Error: Got RST: CANCEL
    at Stream._handleRST (/myproject/node_modules/spdy-transport/lib/spdy-transport/stream.js:265:22)
    at Stream._handleFrame (/myproject/node_modules/spdy-transport/lib/spdy-transport/stream.js:118:10)
    at Connection._handleFrame (/myproject/node_modules/spdy-transport/lib/spdy-transport/connection.js:299:12)
    at Parser.<anonymous> (/myproject/node_modules/spdy-transport/lib/spdy-transport/connection.js:149:10)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at readableAddChunk (/myproject/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:199:16)
    at Parser.Readable.push (/myproject/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:163:10)
    at Parser.Transform.push (/myproject/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at next (/myproject/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:52:12)
```

I didn't notice anything strange in the browser.
I wonder if this is an issue in Chrome or in spdy-transport..?

Versions:
- Chrome 46.0.2490.80 (64-bit)
- spdy: 2.1.0
- spdy-transport: 1.2.1
- Node.js: 5.1.0

**Comment by indutny** [comment]
I think you are using push streams, and not listening for `error` event on them ;)

**Comment by ronkorving** [comment]
I have no push streams in my project.

**Comment by indutny** [comment]
@ronkorving is this easy to reproduce? If yes - may I ask you to collect output with `DEBUG="spdy*"` env variable?

**Comment by ronkorving** [comment]
I have absolutely no idea how it happened :-/ I can't reproduce it yet.
I've been running my project on node-spdy for a while now (not yet 24/7), and this is the first time I see it.

**Comment by ronkorving** [comment]
I, found a way! Just hit refresh really fast in Chrome, and you'll get it. A refresh during a refresh. I'll try to get you some logs (you can imagine the logs are huge when doing what I just described).

**Comment by indutny** [comment]
@ronkorving I think I know what's happening here. Chromium could be sending CANCEL when it wishes to cancel the request that it hasn't yet received reply for.

**Comment by indutny** [comment]
Exactly :) So what do you think if I will make CANCEL a `close` instead of `error` event

**Comment by indutny** [comment]
?

**Comment by ronkorving** [comment]
I don't use spdy-transport directly, so I don't feel like I'm in a position to give advice... But I wouldn't want errors to be logged just because someone hits F5 too fast. Does `http.IncomingMessage` in Node emit `error` when a request gets disconnected?

**Comment by indutny** [comment]
@ronkorving I don't think so. Guess I know what to do.

**Comment by ronkorving** [comment]
Sorry for the trouble, and thanks :)

**Comment by indutny** [comment]
Decided to publish it as a major bump, since it is probably going to break stuff for people. Enjoy spdy@3.0.0 ;)

**Comment by ronkorving** [comment]
Wow, you fixed this in the time it took me to walk to the supermarket? Thanks! :)
