### ISSUE TITLE
Best way to graciously close a 'muxed socket' with `spdy-transport`

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#26]
@indutny what would the best practice you recommend graciously close a muxed socket, without having it blow up in the other side because of the socket hanging up? As in:

```
Uncaught Error: socket hang up
  at Socket.onclose (node_modules/spdy-transport/lib/spdy-transport/connection.js:186:15)
  at TCP._onclose (net.js:477:12)
```

Is listening on the spdy dialer/listener object for 'error' the best option?

Thank you :)

**Comment by diasdavid** [comment]
@indutny I'm back in this issue, `spdy-transport` crashes if there are still streams on the wire that haven't been closed. Where can I catch this error?

**Comment by diasdavid** [comment]
go it. I was not properly listening for 'error' on the dialing side and that was always escaping me:)
