### ISSUE TITLE
`master` is not working (although all tests pass)

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#7]
spdy-transport master branch is not working, although every single test passes.

It throws an error, simply by calling `transport.connection.create`

```
// simple example
var tcp = require('net')
var transport = require('spdy-transport')

tcp.createServer(function (socket) {
  var listener = transport.connection.create(socket, {
    protocol: 'spdy',
    isServer: true
  })
}).listen(8020)
```

```
#  error
» node listener.js                                                                                 
timers.js:165
    throw new TypeError('msecs must be a number');
          ^
TypeError: msecs must be a number
    at Object.exports.enroll (timers.js:165:11)
    at Socket.setTimeout (net.js:337:12)
    at Connection.init [as _init] (/Users/david/Documents/Code/ipfs/mss-spdy-example/node_modules/spdy-transport/lib/spdy-transport/connection.js:168:17)
    at new Connection (/Users/david/Documents/Code/ipfs/mss-spdy-example/node_modules/spdy-transport/lib/spdy-transport/connection.js:126:8)
    at Function.create (/Users/david/Documents/Code/ipfs/mss-spdy-example/node_modules/spdy-transport/lib/spdy-transport/connection.js:132:10)
    at Server.<anonymous> (/Users/david/Documents/Code/ipfs/mss-spdy-example/src/listener-2.js:7:39)
    at Server.emit (events.js:107:17)
    at TCP.onconnection (net.js:1330:8)
```

**Comment by indutny** [comment]
Fixed, sorry about this.

**Comment by diasdavid** [comment]
Thank you :):)
