### ISSUE TITLE
.on('stream') emits a second time when stream.end() is called

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#8]
I'm getting a a second `stream` event emitted after I call stream.end() on the listener side.

Test: https://github.com/diasdavid/abstract-stream-muxer/blob/master/tests/stress-test.js#L17-L63

Run it with node-spdy-stream-muxer[1] - https://github.com/diasdavid/node-spdy-stream-muxer (`npm i && npm test`, it uses tap))

[1] A bit of context, node-spdy-stream-muxer is just a thin veneer on top of spdy-transport to be compatible with abstract-stream-muxer, so that we can run the same battery of tests on several stream-muxer, like we are doing in the Go land - https://github.com/jbenet/go-stream-muxer. Greatly inspired by https://github.com/maxogden/abstract-blob-store

**Comment by diasdavid** [comment]
Updated now to the latest version on `master` branch and got a different error:

```bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at Stream.Writable.write (_stream_writable.js:214:5)
    at /Users/david/Documents/Code/ipfs/node-impl/abstract-stream-muxer/tests/stress-test.js:48:16
    at /Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/connection.js:554:9
    at Object.callback (/Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/stream.js:449:5)
    at Framer.tickSync (/Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:135:12)
    at Framer.tick (/Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:113:13)
    at /Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:107:10
    at process._tickCallback (node.js:355:11)
```

**Comment by indutny** [comment]
@diasdavid are you trying to send body with GET request? ;)

**Comment by diasdavid** [comment]
@indutny thanks :) that makes sense, but it is recent new constraint right?

Nevertheless, the first bug, the double `stream` event still happens

**Comment by indutny** [comment]
Yeah, it is a new constraint to make it work properly with Google servers.

Ok, I have a probable fix. Will push it out once I will finish writing test for it.

**Comment by indutny** [comment]
Thanks for reporting!

**Comment by indutny** [comment]
@diasdavid may I ask you to give it one more try with `master` branch? I hope it is resolved now.

**Comment by diasdavid** [comment]
It is :) Thank you @indutny !
